name: Publish to NuGet (Trusted)

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC (GitHub ↔ NuGet trust)
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore engineering-fort.sln

      - name: Build project
        run: dotnet build engineering-fort.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test EngineeringFort.Tests/EngineeringFort.Tests.csproj --configuration Release --no-build --verbosity normal

      - name: Pack NuGet package
        run: dotnet pack EngineeringFort/EngineeringFort.csproj --configuration Release --no-build -o ./artifacts

      # 🔑 GitHub → NuGet OIDC authentication
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
    
      # 🚀 Publish package to NuGet.org
      - name: NuGet push
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
